
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - /Users/jorgegalvao/jorge-projects/alura-microservices/repo-config
